server:
  port: 9100
spring:
  application:
    name: basic-project-zq-provider
  kafka:
    bootstrap-servers: 172.17.1.36:30081  #多个使用','隔开
    producer:
      retries: 3  #重试次数
      acks: all  #应答级别:多少个分区副本备份完成时向生产者发送ack确认(可选0、1、all/-1)
      properties:
        linger:
          ms: 0  #linger.ms为0表示每接收到一条消息就提交给kafka
      key-serializer: org.apache.kafka.common.serialization.StringSerializer #序列化方式
      value-serializer: org.apache.kafka.common.serialization.StringSerializer #序列化方式
    consumer:
      group-id: zq  # 消费分组 - id
  redis:
    database: 0
    host: 172.17.1.58
    port: 30079
  #jackson配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss #日期格式化
    time-zone: GMT+8
    # 序列化相关
    serialization:
      indent_output: true #化输出
    deserialization:
      fail_on_unknown_properties: false #反序列化时对象没有json对应的属性忽略
    #    defaultPropertyInclusion: NON_EMPTY #如何序列化
    parser:
      allow_unquoted_control_chars: true #允许特殊和转义符
      allow_single_quotes: true #允许单引号
  elasticsearch:
    rest:
      uris: http://172.17.1.43:9200
      username: elastic
      password: hurricane


swagger2:
  title: 张骞-测试
  version: 0.0.1-SNAPSHOT
  description: 祸兮福之所倚,福兮祸之所伏
  contact:
    name: zq
    url: www.zq.com
    email: 1052591242@qq.com