server:
  port: 9200
spring:
  application:
    name: basic-project-zq-provider
  datasource:
    dynamic:
      p6spy: true
      datasource:
        master:
          username: root
          password: www123456
          url: jdbc:mysql://127.0.0.1:3306/ceshi?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
          driver-class-name: com.mysql.cj.jdbc.Driver
#通过p6spy打印日志配置
#        slave:
#          username: root
#          password: www123456
#          url: jdbc:p6spy:mysql://127.0.0.1:3306/ceshi?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
#          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  kafka:
    bootstrap-servers: 172.17.1.36:30092  #多个使用','隔开
    producer:
      retries: 3  #重试次数
      acks: all  #应答级别:多少个分区副本备份完成时向生产者发送ack确认(可选0、1、all/-1)
      properties:
        linger:
          ms: 0  #linger.ms为0表示每接收到一条消息就提交给kafka
      key-serializer: org.apache.kafka.common.serialization.StringSerializer #序列化方式
      value-serializer: org.apache.kafka.common.serialization.StringSerializer #序列化方式
    consumer:
      group-id: zq  # 消费分组 - id
  redis:
    database: 0
    host: 172.17.1.58
    port: 30079
  #jackson配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss #日期格式化
    time-zone: GMT+8
    # 序列化相关
    serialization:
      indent_output: true #化输出
    deserialization:
      fail_on_unknown_properties: false #反序列化时对象没有json对应的属性忽略
    #    defaultPropertyInclusion: NON_EMPTY #如何序列化
    parser:
      allow_unquoted_control_chars: true #允许特殊和转义符
      allow_single_quotes: true #允许单引号
  elasticsearch:
    rest:
      uris: http://172.17.1.43:9200
      username: elastic
      password: hurricane
  servlet:
    multipart:
      max-file-size: 104857600  #100m

#mybatis-plus:
#  mapper-locations: classpath*:com/supconit/its/itp/**/**/mapper/*Mapper.xml
#  type-aliases-package: com.supconit.its.itp.information.**.dto.*
#  global-config:
#    db-config:
#      id-type: auto
#      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
#      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)




fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 172.17.1.34:22122
  #    - 33.94.232.85:22122
  pool:
    #开启可能导致获取不到线程池,从而导致报错
    test-on-borrow: false
#    #从池中借出的对象的最大数目（配置为-1表示不限制）
#    max-total: -1
#    #获取连接时的最大等待毫秒数(默认配置为5秒)
#    max-wait-millis: 5000
#    #每个key最大连接数
#    max-total-per-key: 50
#    #每个key对应的连接池最大空闲连接数
#    max-idle-per-key: 10
#    #每个key对应的连接池最小空闲连接数
#    min-idle-per-key: 5


swagger2:
  title: 张骞-测试
  version: 0.0.1-SNAPSHOT
  description: 祸兮福之所倚,福兮祸之所伏
  contact:
    name: zq
    url: www.zq.com
    email: 1052591242@qq.com